/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CustomerProfile } from "./CustomerProfile";
import { CustomerProfileCountArgs } from "./CustomerProfileCountArgs";
import { CustomerProfileFindManyArgs } from "./CustomerProfileFindManyArgs";
import { CustomerProfileFindUniqueArgs } from "./CustomerProfileFindUniqueArgs";
import { CreateCustomerProfileArgs } from "./CreateCustomerProfileArgs";
import { UpdateCustomerProfileArgs } from "./UpdateCustomerProfileArgs";
import { DeleteCustomerProfileArgs } from "./DeleteCustomerProfileArgs";
import { CustomerProfileService } from "../customerProfile.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => CustomerProfile)
export class CustomerProfileResolverBase {
  constructor(
    protected readonly service: CustomerProfileService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CustomerProfile",
    action: "read",
    possession: "any",
  })
  async _customerProfilesMeta(
    @graphql.Args() args: CustomerProfileCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CustomerProfile])
  @nestAccessControl.UseRoles({
    resource: "CustomerProfile",
    action: "read",
    possession: "any",
  })
  async customerProfiles(
    @graphql.Args() args: CustomerProfileFindManyArgs
  ): Promise<CustomerProfile[]> {
    return this.service.customerProfiles(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CustomerProfile, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CustomerProfile",
    action: "read",
    possession: "own",
  })
  async customerProfile(
    @graphql.Args() args: CustomerProfileFindUniqueArgs
  ): Promise<CustomerProfile | null> {
    const result = await this.service.customerProfile(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CustomerProfile)
  @nestAccessControl.UseRoles({
    resource: "CustomerProfile",
    action: "create",
    possession: "any",
  })
  async createCustomerProfile(
    @graphql.Args() args: CreateCustomerProfileArgs
  ): Promise<CustomerProfile> {
    return await this.service.createCustomerProfile({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CustomerProfile)
  @nestAccessControl.UseRoles({
    resource: "CustomerProfile",
    action: "update",
    possession: "any",
  })
  async updateCustomerProfile(
    @graphql.Args() args: UpdateCustomerProfileArgs
  ): Promise<CustomerProfile | null> {
    try {
      return await this.service.updateCustomerProfile({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CustomerProfile)
  @nestAccessControl.UseRoles({
    resource: "CustomerProfile",
    action: "delete",
    possession: "any",
  })
  async deleteCustomerProfile(
    @graphql.Args() args: DeleteCustomerProfileArgs
  ): Promise<CustomerProfile | null> {
    try {
      return await this.service.deleteCustomerProfile(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
