/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PatientScheduleService } from "../patientSchedule.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PatientScheduleCreateInput } from "./PatientScheduleCreateInput";
import { PatientSchedule } from "./PatientSchedule";
import { PatientScheduleFindManyArgs } from "./PatientScheduleFindManyArgs";
import { PatientScheduleWhereUniqueInput } from "./PatientScheduleWhereUniqueInput";
import { PatientScheduleUpdateInput } from "./PatientScheduleUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PatientScheduleControllerBase {
  constructor(
    protected readonly service: PatientScheduleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PatientSchedule })
  @nestAccessControl.UseRoles({
    resource: "PatientSchedule",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPatientSchedule(
    @common.Body() data: PatientScheduleCreateInput
  ): Promise<PatientSchedule> {
    return await this.service.createPatientSchedule({
      data: data,
      select: {
        appointmentDate: true,
        appointmentReason: true,
        appointmentTime: true,
        createdAt: true,
        doctorName: true,
        id: true,
        patientName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PatientSchedule] })
  @ApiNestedQuery(PatientScheduleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PatientSchedule",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async patientSchedules(
    @common.Req() request: Request
  ): Promise<PatientSchedule[]> {
    const args = plainToClass(PatientScheduleFindManyArgs, request.query);
    return this.service.patientSchedules({
      ...args,
      select: {
        appointmentDate: true,
        appointmentReason: true,
        appointmentTime: true,
        createdAt: true,
        doctorName: true,
        id: true,
        patientName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PatientSchedule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PatientSchedule",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async patientSchedule(
    @common.Param() params: PatientScheduleWhereUniqueInput
  ): Promise<PatientSchedule | null> {
    const result = await this.service.patientSchedule({
      where: params,
      select: {
        appointmentDate: true,
        appointmentReason: true,
        appointmentTime: true,
        createdAt: true,
        doctorName: true,
        id: true,
        patientName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PatientSchedule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PatientSchedule",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePatientSchedule(
    @common.Param() params: PatientScheduleWhereUniqueInput,
    @common.Body() data: PatientScheduleUpdateInput
  ): Promise<PatientSchedule | null> {
    try {
      return await this.service.updatePatientSchedule({
        where: params,
        data: data,
        select: {
          appointmentDate: true,
          appointmentReason: true,
          appointmentTime: true,
          createdAt: true,
          doctorName: true,
          id: true,
          patientName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PatientSchedule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PatientSchedule",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePatientSchedule(
    @common.Param() params: PatientScheduleWhereUniqueInput
  ): Promise<PatientSchedule | null> {
    try {
      return await this.service.deletePatientSchedule({
        where: params,
        select: {
          appointmentDate: true,
          appointmentReason: true,
          appointmentTime: true,
          createdAt: true,
          doctorName: true,
          id: true,
          patientName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
