/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PatientRegistrationFormService } from "../patientRegistrationForm.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PatientRegistrationFormCreateInput } from "./PatientRegistrationFormCreateInput";
import { PatientRegistrationForm } from "./PatientRegistrationForm";
import { PatientRegistrationFormFindManyArgs } from "./PatientRegistrationFormFindManyArgs";
import { PatientRegistrationFormWhereUniqueInput } from "./PatientRegistrationFormWhereUniqueInput";
import { PatientRegistrationFormUpdateInput } from "./PatientRegistrationFormUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PatientRegistrationFormControllerBase {
  constructor(
    protected readonly service: PatientRegistrationFormService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PatientRegistrationForm })
  @nestAccessControl.UseRoles({
    resource: "PatientRegistrationForm",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPatientRegistrationForm(
    @common.Body() data: PatientRegistrationFormCreateInput
  ): Promise<PatientRegistrationForm> {
    return await this.service.createPatientRegistrationForm({
      data: data,
      select: {
        address: true,
        createdAt: true,
        dateOfBirth: true,
        email: true,
        emergencyContact: true,
        fullName: true,
        id: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PatientRegistrationForm] })
  @ApiNestedQuery(PatientRegistrationFormFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PatientRegistrationForm",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async patientRegistrationForms(
    @common.Req() request: Request
  ): Promise<PatientRegistrationForm[]> {
    const args = plainToClass(
      PatientRegistrationFormFindManyArgs,
      request.query
    );
    return this.service.patientRegistrationForms({
      ...args,
      select: {
        address: true,
        createdAt: true,
        dateOfBirth: true,
        email: true,
        emergencyContact: true,
        fullName: true,
        id: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PatientRegistrationForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PatientRegistrationForm",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async patientRegistrationForm(
    @common.Param() params: PatientRegistrationFormWhereUniqueInput
  ): Promise<PatientRegistrationForm | null> {
    const result = await this.service.patientRegistrationForm({
      where: params,
      select: {
        address: true,
        createdAt: true,
        dateOfBirth: true,
        email: true,
        emergencyContact: true,
        fullName: true,
        id: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PatientRegistrationForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PatientRegistrationForm",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePatientRegistrationForm(
    @common.Param() params: PatientRegistrationFormWhereUniqueInput,
    @common.Body() data: PatientRegistrationFormUpdateInput
  ): Promise<PatientRegistrationForm | null> {
    try {
      return await this.service.updatePatientRegistrationForm({
        where: params,
        data: data,
        select: {
          address: true,
          createdAt: true,
          dateOfBirth: true,
          email: true,
          emergencyContact: true,
          fullName: true,
          id: true,
          phoneNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PatientRegistrationForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PatientRegistrationForm",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePatientRegistrationForm(
    @common.Param() params: PatientRegistrationFormWhereUniqueInput
  ): Promise<PatientRegistrationForm | null> {
    try {
      return await this.service.deletePatientRegistrationForm({
        where: params,
        select: {
          address: true,
          createdAt: true,
          dateOfBirth: true,
          email: true,
          emergencyContact: true,
          fullName: true,
          id: true,
          phoneNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
