/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  PatientRegistrationForm as PrismaPatientRegistrationForm,
} from "@prisma/client";

export class PatientRegistrationFormServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PatientRegistrationFormCountArgs, "select">
  ): Promise<number> {
    return this.prisma.patientRegistrationForm.count(args);
  }

  async patientRegistrationForms(
    args: Prisma.PatientRegistrationFormFindManyArgs
  ): Promise<PrismaPatientRegistrationForm[]> {
    return this.prisma.patientRegistrationForm.findMany(args);
  }
  async patientRegistrationForm(
    args: Prisma.PatientRegistrationFormFindUniqueArgs
  ): Promise<PrismaPatientRegistrationForm | null> {
    return this.prisma.patientRegistrationForm.findUnique(args);
  }
  async createPatientRegistrationForm(
    args: Prisma.PatientRegistrationFormCreateArgs
  ): Promise<PrismaPatientRegistrationForm> {
    return this.prisma.patientRegistrationForm.create(args);
  }
  async updatePatientRegistrationForm(
    args: Prisma.PatientRegistrationFormUpdateArgs
  ): Promise<PrismaPatientRegistrationForm> {
    return this.prisma.patientRegistrationForm.update(args);
  }
  async deletePatientRegistrationForm(
    args: Prisma.PatientRegistrationFormDeleteArgs
  ): Promise<PrismaPatientRegistrationForm> {
    return this.prisma.patientRegistrationForm.delete(args);
  }
}
